import Head from "next/head"
import Navbar from "../components/Navbar"
import Footer from "../components/Footer"
// import "tailwindcss/tailwind.css"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Daga | Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </div>
  )
}
